### ISSUE TITLE
storeTransaction field is needed for onPurchaseSuccess function parameter

### ISSUE THREAD

**Issue by maykfery** [adaptyteam/AdaptyUI-Android#1]
I need to post back storeTransaction information to 3rd party trackers but I cannot get that value after a successful purchase. It would be good to add store transaction (signature and originalJSON) as a parameter on onPurchaseSuccess function of AdaptyUiEventListener.

**Comment by vladd-g** [comment]
@maykfery thanks you, we'll add it in future releases

**Comment by vladd-g** [comment]
@maykfery we've added the transaction information to [onPurchaseSuccess](https://kotlin.adapty.io/adapty-ui/com.adapty.ui.listeners/-adapty-ui-event-listener/on-purchase-success). Please update to [v2.1.2](https://github.com/adaptyteam/AdaptyUI-Android/releases/tag/2.1.2) and [v2.10.0](https://github.com/adaptyteam/AdaptySDK-Android/releases/tag/2.10.0)
